### ISSUE TITLE
incorrect valors for memory and network

### ISSUE THREAD

**Issue by fanabordo** [XavierBerger/RPi-Monitor#192] opened 2017-08-21 12:53 UTC
hi, how do you get correct valors for memory (Used: NaNkB (NaN%) Available: NaNkB Total: 927.32MB) and network (Used: NaNkB (NaN%) Available: NaNkB) plz? thx by advance

**Comment by martignoni** [comment] 2017-08-24 09:03
This is a dupe of #191

**Comment by martignoni** [comment] 2017-08-24 09:22
See https://github.com/XavierBerger/RPi-Monitor/issues/191#issuecomment-324581792 for a partial solution

**Comment by XavierBerger** [comment] 2017-08-26 10:11
In the latest Raspbian, the parameters of `free` command has changed.
I will fix that in v2.12 - I don't know yet when I'll publish this version but I should do it soon to fix such bugs...

**Closed by XavierBerger** 2017-08-26 10:11 UTC

**Comment by ezaul** [comment] 2020-07-02 23:19
@fanabordo   se estiver usando NTFS   use fuseblk em vez de ntfs 
static.10.source = df -t fuseblk
