### ISSUE TITLE
rpi monitor error dynamic.json

### ISSUE THREAD

**Issue by mdiharce** [XavierBerger/RPi-Monitor#139] opened 2016-01-14 19:20 UTC
Hello there! Yesterday RPI install Monitor, after a few hours appeared to be using me the error: Error dynamic.json RPI monitor and failed to show the information you gave.
Anyone know how to solve that problem?
Thank you!

**Comment by XavierBerger** [comment] 2016-08-12 12:21
As we can't reproduce this error, I'm closing it. If it occurs again you can reopen this issue and add details.

**Closed by XavierBerger** 2016-08-12 12:21 UTC
